name: Deploy React App to GitHub Pages

on:
  push:
    branches:
      - main # Esegui questo workflow ogni volta che ci sono push sul branch main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest # Esegui il job su una macchina virtuale Ubuntu

    steps:
      - name: Checkout repository # Scarica il codice del tuo repository
        uses: actions/checkout@v3

      - name: Set up Node.js # Configura Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20" # O '20.x' # Usa Node.js versione 18 (o quella compatibile con il tuo progetto)

      - name: Install dependencies # Installa le dipendenze del progetto
        run: yarn install # O 'npm install' se usi npm

      - name: Build React app # Esegui la build della tua applicazione React
        run: yarn build # O 'npm run build' se usi npm

      - name: Deploy to GitHub Pages # Pubblica l'app sulla tua pagina GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }} # Token fornito automaticamente da GitHub
          publish_dir: ./build # La cartella che contiene i file di output della build
